name: Run Tavern for API testing

run-name: Run Tavern for API testing

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  api_test:
    permissions:
      contents: read
      checks: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pipenv # NOTE: キャッシュの有効化

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dev-packages
        run: |
          pipenv install --dev

      - name: Run Tavern by pytest
        run: |
          pipenv run pytest -vv --tb=short --alluredir=allure-results

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results # このデータを基に、
          allure_history: allure-history # このディレクトリにレポートを生成

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history # レポートをGitHub Pagesへ配信
